# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [3]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [5]:
arr = [1,2,3,4,5,6,7]
numpy = np.array(arr)
numpy

array([1, 2, 3, 4, 5, 6, 7])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [36]:
arr = np.zeros((1,2,3,4,5,6,7,8,9))

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [29]:
arr = np.random.randn(10)
arr.size
arr.itemsize

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
help(np.add)
np.info(np.add)

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [6]:
arr = np.zeros(shape=(1,2,3,4,5,6,7,8,9,10,11,12))
arr[0,0,0,0,0,0,0,0,0,0,0,5] = 1

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [7]:
arr = range(20,60)

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [8]:
arr = np.random.rand(6)

arr1 = arr[::-1]

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [9]:
arr1 = np.arange(12,21).reshape(3, 3)

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [10]:
arr = [3, 7, 0, 0, 9, 0]

arr1 = np.nonzero(arr)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [11]:
arr = np.random.randint(10, size=(2,2,2))

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [12]:
array = np.random.randint(10,size=(9,9))


minimum = [element for row in array for element in row]

kichik = min(minimum)


maksimum = [element for row in array for element in row]

katta = max(maksimum)

print(kichik,katta)

0 9


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [13]:
Nan = ["nan","False","False","nan","True","False"]

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [14]:
x = np.ones((6,3))
y = np.ones((3,4))
np.dot(x,y)

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [15]:
print(9,10)

9 10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [16]:
a = np.array([1,2])
b = np.array([4,5])
a1 = a>b
a2 = a>=b
a3 = a<b
a4 = a<=b

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [17]:
tekshirish = ["nan", "nan", 0]

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [18]:
x = np.array([1,2,3,4,5,6])
y = np.array([4,5,6,7,8,9])

bir_xil = np.intersect1d(x,y)

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [19]:
arr = np.random.randn(10)
musbat = arr[arr>0]
# % belsigini qatnashtirib ishlatishni bilmadim !!!
butun1 = np.floor(musbat)
butun2 = musbat.astype(int)
butun3 = np.trunc(musbat)

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [20]:
arr = np.random.randint(3, size=(3,3))

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [21]:
arr = np.random.randn(10)

tartiblangan = sorted(arr)

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [22]:
x = np.random.randn(10)
y = np.random.randn(10)

tekshir1 = np.allclose(x, y)
tekshir2 = np.array_equal(x, y)

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [23]:
x = np.random.randint(10, size=(6,3))
y = np.random.randint(10, size=(3,4))

kupaytma = np.dot(x,y)

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [24]:
x = np.random.randn(5)
katta = np.argmax(x)
x[katta] = 0

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [30]:
bugun = np.datetime64('today', 'D')
kecha = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
ertaga= np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print("kecha : ",kecha)
print("bugun : ", bugun)
print("ertaga: ", ertaga)

kecha :  2023-11-07
bugun :  2023-11-08
ertaga:  2023-11-09


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [31]:
start_date = np.datetime64('2016-01-01')

end_date = np.datetime64('2016-02-01')

all_dates = np.arange(start_date, end_date, np.timedelta64(1, 'D'))
print(all_dates)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [32]:
arr = np.random.randn(10)

musbat = arr[arr>0]

musbat_tasodifiy = np.random.choice(musbat)

butun1 = np.floor(musbat_tasodifiy)
butun2 = musbat_tasodifiy.astype(int)
butun3 = np.trunc(musbat_tasodifiy)

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [33]:
x = np.random.randn(10)
y = np.random.randn(10)
z = np.random.randn(10)
# Shu funksiyaga tushunmadim va natijasi ham qandaydir boshqacha chiqib qoldi !!!
summa = np.add.reduce([x, y, z])

print(summa)


[-1.61775759 -0.67329593 -1.12822816 -0.02352202 -0.30808381  0.08900269
  1.95804581 -1.45608356  0.13955276  0.53147477]


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [4]:
a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
a = np.array(a)
new_shape = (11, 4)
new_strides = (a.itemsize, a.itemsize)


def create_strided_array(arr, shape, strides):
    return np.lib.stride_tricks.as_strided(arr, shape=shape, strides=strides)

y = create_strided_array(a, shape=new_shape, strides=new_strides)

print(y)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [35]:
arr = np.random.randint(low=0, high=100, size=10)

qushiladigan_massiv = np.array([1,2,3,4,5,6,7,8,9])
yangi = np.append(arr, qushiladigan_massiv)
#Dastur to'liq emas !!!

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

In [34]:
# Ixtiyoriy ikkita massiv  a va b .  amassiv ichidan 2 ga bo'linadiganlar yani juft sonlarni where funksiyasi bilan ajratib olmoqchiman.
# Bor bo'lsa o'sha son chiqadi, agar yo'q bo'lsa NaN chiqadi.
#ikkita massiv elementlari o'lchami teng bo'lishi kerak.
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array(["NaN","NaN","NaN","NaN","NaN","NaN","NaN","NaN","NaN"])


tekshirish = np.where((a%2==0), a, b)


print(tekshirish)


['NaN' '2' 'NaN' '4' 'NaN' '6' 'NaN' '8' 'NaN']
